### ISSUE TITLE
老哥，你的网站似乎没备案，不能直接访问

### ISSUE THREAD

**Issue by UnlightedOtaku** [vimerzhao/vimerzhao.github.io#8]
不过我ping了一下，直接通过ip访问了

**Comment by vimerzhao** [comment]
是的，还在备案中，现在只能通过ip [http://111.229.130.216/](http://111.229.130.216/) 访问，你还ping反查id，也太秀了。

**Comment by Cactusinhand** [comment]
还是404状态 😿

**Comment by vimerzhao** [comment]
> 还是404状态 😿

http://vimerzhao.top/
